-- Smart Attendance System schema (PostgreSQL / Supabase)
--
-- Mirrors database/schema.sql (SQLite) exactly in shape. Two deliberate
-- differences, both chosen so the two backends behave identically at runtime:
--
--   1. Identifiers stay UNQUOTED, so Postgres folds them to lowercase. Queries
--      in routes/ are also unquoted, so they match. The application never sees
--      the difference because modules/db.py maps rows into a case-insensitive
--      Row, which is what lets templates keep writing {{ s.MatricNo }}.
--
--   2. Date/StartTime/EndTime/Timestamp are TEXT, not DATE/TIMESTAMP. SQLite
--      returns these as strings, and the templates slice them directly
--      ({{ s.StartTime[11:16] }}) and compare them as strings. Real timestamp
--      columns would return datetime objects here and break both. ISO-8601
--      text sorts lexicographically, so ORDER BY and BETWEEN still work, and
--      every date calculation in this app already happens in Python.

CREATE TABLE IF NOT EXISTS Student (
    StudentID      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FullName       TEXT NOT NULL,
    MatricNo       TEXT NOT NULL UNIQUE,   -- typed by the student at attendance time
    Department     TEXT,
    Level          TEXT,
    FaceEmbeddings TEXT                    -- JSON array of 128-d embedding vectors
);

-- "User" is a reserved word in Postgres, so this one table is quoted here and
-- in every query that touches it. db.py rewrites `User` -> `"User"` on the
-- Postgres backend so routes/ can keep using the unquoted SQLite spelling.
CREATE TABLE IF NOT EXISTS "User" (
    UserID           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username         TEXT NOT NULL UNIQUE,
    PasswordHash     TEXT NOT NULL,
    Role             TEXT NOT NULL CHECK (Role IN ('admin', 'lecturer', 'student')),
    FullName         TEXT,
    LinkedStudentID  INTEGER REFERENCES Student(StudentID)
);

CREATE TABLE IF NOT EXISTS Course (
    CourseID   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CourseCode TEXT NOT NULL,
    CourseName TEXT NOT NULL,
    LecturerID INTEGER REFERENCES "User"(UserID),  -- role = lecturer
    Department TEXT
);

-- Course roster: which students are registered in which course. Kiosk
-- verification and all reports operate on this list, never on all students.
CREATE TABLE IF NOT EXISTS CourseStudent (
    CourseID  INTEGER NOT NULL REFERENCES Course(CourseID),
    StudentID INTEGER NOT NULL REFERENCES Student(StudentID),
    PRIMARY KEY (CourseID, StudentID)
);

CREATE TABLE IF NOT EXISTS Session (
    SessionID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CourseID  INTEGER NOT NULL REFERENCES Course(CourseID),
    Date      TEXT NOT NULL,
    StartTime TEXT NOT NULL,
    EndTime   TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Attendance (
    AttendanceID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    StudentID    INTEGER NOT NULL REFERENCES Student(StudentID),
    CourseID     INTEGER NOT NULL REFERENCES Course(CourseID),
    SessionID    INTEGER NOT NULL REFERENCES Session(SessionID),
    Status       TEXT NOT NULL CHECK (Status IN ('present', 'absent', 'flagged_manual_review')),
    -- routes/admin.py inserts a manual correction without naming this column,
    -- so it needs a default. to_char() reproduces the exact 'YYYY-MM-DD HH:MM:SS'
    -- string shape the rest of the app writes and the templates slice.
    Timestamp    TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE (StudentID, SessionID)           -- no duplicate attendance, enforced at DB level
);

-- Runtime-tunable settings (similarity threshold, attendance % alert level)
CREATE TABLE IF NOT EXISTS Settings (
    Key   TEXT PRIMARY KEY,
    Value TEXT NOT NULL
);
